apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
  namespace: dev
type: kubernetes.io/dockerconfigjson
data:
  
  .dockerconfigjson: e2F1dGhzOnsxMC4wLjk0LjQzOnt1c2VybmFtZTphZG1pbixwYXNzd29yZDowNDAzMjcxMTAwLGVtYWlsOmFkZWxlbG5pbXIzMkBnbWFpbC5jb20sYXV0aDpZV1J0YVc0Nk1EUXdNekkzTVRFd01Bbz19fX0K
