apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
  namespace: dev
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded JSON for https://10.0.76.98:5000
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovLzEwLjAuNzYuOTg6NTAwMCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiIwNDAzMjcxMTAwIiwiZW1haWwiOiJhZGVsZWxuaW1yMzJAZ21haWwuY29tIiwiYXV0aCI6IllXUnRhVzQ2TURRd016STNNRUV3TUE9PSJ9fX0=